### ISSUE TITLE
NXF_CONTAINER_ENTRYPOINT_OVERRIDE defaults to false as of Nextflow v 22.08.0

### ISSUE THREAD

**Issue by raqmejtru** [trev-f/SRAlign#34]
Hi! I've been trying to get the test run working but kept getting the following error message:
```
ERROR ~ Error executing process > 'SRAlign:ReadsQC:ReadsMultiQC (ATAC-seq_Celegans_design_reads_-_angry_golick_-_2023-07-21_10-49)'

Caused by:
  Process `SRAlign:ReadsQC:ReadsMultiQC (ATAC-seq_Celegans_design_reads_-_angry_golick_-_2023-07-21_10-49)` terminated with an error exit status (2)

Command executed:

  multiqc             -n ATAC-seq_Celegans_design_reads_-_angry_golick_-_2023-07-21_10-49__mqc-reads             --module fastqc             hmg-3_rep2__fqc_R1_fastqc.zip hmg-3_rep2__fqc_R2_fastqc.zip hmg-3_rep1__fqc_R1_fastqc.zip hmg-3_rep1__fqc_R2_fastqc.zip hmg-3_rep2__fsp_fqc_R1_fastqc.zip hmg-3_rep2__fsp_fqc_R2_fastqc.zip hmg-3_rep1__fsp_fqc_R1_fastqc.zip hmg-3_rep1__fsp_fqc_R2_fastqc.zip

Command exit status:
  2

Command output:
  (empty)

Command error:
  Usage: multiqc [OPTIONS] <analysis directory>

  Error: Invalid value for '-c' / '--config': Path 'eval export PATH="$PATH:/home/raquel/.nextflow/assets/trev-f/SRAlign/bin"; /bin/bash .command.run nxf_trace' does not exist.

  This is MultiQC v1.11

  For more help, run 'multiqc --help' or visit http://multiqc.info

Work dir:
  /home/raquel/test-SRAlign/work/62/c7352db1945be910bbc73c183f237b

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
```

The `docker run -i --cpu-shares 1024 --memory 2048m -e "NXF_DEBUG=${NXF_DEBUG:=0}" -v /home/raquel:/home/raquel -w "$PWD" --name $NXF_BOXID ewels/multiqc:v1.11 /bin/bash -c "eval $(nxf_container_env); /bin/bash /home/raquel/test-SRAlign/work/66/5f440fed6865d7f8b62e201a9be293/.command.run nxf_trace"` command in the  `.command.run` file within the ReadsMultiQC process was being misinterpreted. 

Seems like it's because Nextflow>=22.08.0 does not automatically use `/bin/bash` as the entry point. 
https://github.com/nextflow-io/nextflow/discussions/3357

Test run works now if I set `export NXF_CONTAINER_ENTRYPOINT_OVERRIDE=true`

Might be useful to add that to the documentation install instructions here and on SRAtac repo.

**Comment by trev-f** [comment]
Thanks for raising an issue! I'm happy to add that workaround to the docs. However, I find that workarounds like setting environment variables aren't always a stable solution since they're often forgotten or get buried in `.bashrc` files. Would you be willing to help me find a better solution? I'm currently running Nextflow 21.04 and am afraid of any potentially breaking changes from upgrading since I use it pretty much daily right now.

It looks like there's another potential workaround in that same issue: https://github.com/nextflow-io/nextflow/discussions/3357#discussioncomment-4078096

Can you try the following for me?

1. Start a new shell session so that the variable `NXF_CONTAINER_ENTRYPOINT_OVERRIDE` is no longer set to `true` (you can verify this with `echo $NXF_CONTAINER_ENTRYPOINT_OVERRIDE`; this command should not return `true` in your new session).
2. Create and enter a new directory for this test.
3. Inside your new test directory implement the fix from the issue above: create a `nextlow.config` file that contains the following lines:
```
docker {
    docker.runOptions = '--entrypoint=""'
}
```
4. Run the test including your config to see if this fix worked: `nextflow run trev-f/SRAlign -profile test -c nextflow.config`

Let me know what the outcome is and we can figure out how to proceed from there.

**Comment by raqmejtru** [comment]
Thanks for the quick response. 

The same error appears when I add the following to the nextflow.config file.
```
docker {
    docker.runOptions = '--entrypoint=""'
}
```
However, adding `docker.runOptions` within the profiles chunk seems to apply the desired modification.
```
profiles {
    test {
        docker.enabled     = true
        docker.runOptions  = '--entrypoint=""'
        params.maxMemory   = '4.GB'
        params.input       = 'https://github.com/trev-f/SRAlign-test/raw/main/inputs/ATAC-seq_Celegans_design_reads.csv'
        params.genome      = 'testWBcel235'
        params.contaminant = 'testEB1'
    }
}
```

Maybe adding `docker.runOptions  = '--entrypoint=""'` to each profile in the pipeline `nextflow.config` file could be a solution, or somehow applying to all profiles? I'm not sure why your suggestion didn't accomplish that, but I'm fairly new to Nextflow and its hierarchies.

**Comment by raqmejtru** [comment]
Sorry didn't mean to close the issue!

**Comment by trev-f** [comment]
No worries! And thanks for trying out the fix so quickly.

What if you do

```
docker {
    runOptions = '--entrypoint=""'
}
```

in `nextflow.config` instead.

Also, once we get this figured out would you be interested in adding the fix into this repo and in `SRAtac` as well? It might be good experience for both of us to contribute to and manage open source projects.

**Comment by raqmejtru** [comment]
That worked! I will add the fix into both repos soon. Thanks again for the help.

**Comment by trev-f** [comment]
Glad to hear it!

In case you need it, here's the [guide for making contributions to public repos](https://docs.github.com/en/get-started/quickstart/contributing-to-projects). It's what I've followed the couple of times I've made PRs.

ETA: I'll leave this issue open until that fix PR comes in. Thanks for your work on this!
